package com.proyecto.terranova.config.enums;

public enum DepartamentoEnum {
    AMAZONAS,
    ANTIOQUIA,
    ARAUCA,
    ATLÁNTICO,
    BOLÍVAR,
    BOYACÁ,
    CALDAS,
    CAQUETÁ,
    CASANARE,
    CAUCA,
    CESAR,
    CHOCÓ,
    CÓRDOBA,
    CUNDINAMARCA,
    GUAINÍA,
    GUAVIARE,
    HUILA,
    LA_GUAJIRA,
    MAGDALENA,
    META,
    NARIÑO,
    NORTE_DE_SANTANDER,
    PUTUMAYO,
    QUINDÍO,
    RISARALDA,
    SAN_ANDRES_Y_PROVIDENCIA,
    SANTANDER,
    SUCRE,
    TOLIMA,
    VALLE_DEL_CAUCA,
    VAUPÉS,
    VICHADA,
}
